Add prisma protocol class
airtai/fastagencyapi pull request #6
Opened 2024-07-25 04:47 UTC by kumaranvpl

# Description

Please include a summary of the change and specify which issue is being addressed. Additionally, provide relevant motivation and context.

Fixes # (issue number)

## Type of change

Please delete options that are not relevant.

- [ ] Documentation (typos, code examples, or any documentation updates)
- [ ] Bug fix (a non-breaking change that resolves an issue)
- [ ] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a fix or feature that would disrupt existing functionality)
- [ ] This change requires a documentation update

## Checklist

- [ ] My code adheres to the style guidelines of this project (`scripts/lint.sh` shows no errors)
- [ ] I have conducted a self-review of my own code
- [ ] I have made the necessary changes to the documentation
- [ ] My changes do not generate any new warnings
- [ ] I have added tests to validate the effectiveness of my fix or the functionality of my new feature
- [ ] Both new and existing unit tests pass successfully on my local environment by running `scripts/test-cov.sh`
- [ ] I have ensured that static analysis tests are passing by running `scripts/static-anaylysis.sh`
- [ ] I have included code examples to illustrate the modifications

2024-07-31 07:17 UTC, davorrunje requested changes

2024-07-31 07:17 UTC, davorrunje commented on fastagency/db/inmemory.py
> +from fastapi import HTTPException
should not import it

2024-07-31 07:17 UTC, davorrunje commented on fastagency/db/prisma.py
> +from fastapi import HTTPException
remove this: should return our Exceptions

2024-07-31 07:17 UTC, davorrunje commented on fastagency/models/agents/base.py
> +            toolbox_dict = await BackendDBProtocol.db().find_model(
why do we need find_model in agents but not in any other model?

2024-08-13 06:18 UTC, davorrunje approved these changes

2024-08-13 06:35 UTC, merged

2024-08-14 04:42 UTC, kumaranvpl commented
Fixes #9